# Generated by Django 2.0.2 on 2018-02-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_auto_20180216_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='open_farms_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='open_farms_id',
        ),
        migrations.AddField(
            model_name='producer',
            name='open_farms_url',
            field=models.URLField(default='dummyurl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='open_farms_url',
            field=models.URLField(default='dummyurl'),
            preserve_default=False,
        ),
    ]
