# Generated by Django 2.0.2 on 2018-02-16 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baslerbauer_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.PositiveIntegerField()),
                ('date_time', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baslerbauer_main.Consumer')),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='producer',
        ),
        migrations.AddField(
            model_name='producer',
            name='open_farms_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='open_farms_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.AddField(
            model_name='transaction',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baslerbauer_main.Producer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baslerbauer_main.Product'),
        ),
        migrations.AddField(
            model_name='stock',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baslerbauer_main.Producer'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baslerbauer_main.Product'),
        ),
    ]
