# Generated by Django 2.0.2 on 2018-02-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baslerbauer_main', '0003_auto_20180216_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='open_farms_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='open_farms_url',
        ),
        migrations.AddField(
            model_name='producer',
            name='openfarms_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='openfarms_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
