# Generated by Django 2.0.2 on 2018-02-16 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baslerbauer_main', '0004_auto_20180216_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
