# Generated by Django 2.0.2 on 2018-02-16 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baslerbauer_main', '0005_producer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
