# Generated by Django 2.0.2 on 2018-02-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baslerbauer_main', '0009_transactiongroupcounter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiongroupcounter',
            old_name='group',
            new_name='value',
        ),
    ]
